1101861: retry the next link if no response found and all records method changes
HireFrederick/frederick_api_gem pull request #20
Opened 2022-07-11 05:11 UTC by nileshpatil-mindbody

1101861: retry the next link if no response found and all records method changes
Ticket: [1101861](https://dev.azure.com/mindbody/Marketing%20Products/_workitems/edit/1101861)

2022-07-11 12:02 UTC, moizmb requested changes
I dont see any tests for this, can you add them please

2022-07-12 09:23 UTC, moizmb commented on Dockerfile
> +FROM ruby:2.7.0
why is this required?

2022-07-12 14:40 UTC, otheogar commented on lib/frederick_api/v2/helpers/paginator.rb
> +        def next_result_set(current_result_set)
I think we should make this a private method and add to the tests for all_records - add tests for when the current result set is empty.

2022-07-12 17:28 UTC, otheogar approved these changes

2022-07-13 09:31 UTC, moizmb commented on spec/frederick_api/v2/helpers/paginator_spec.rb
> +        expect(paginator).to receive(:next).with(no_args).and_return(new_result_set2)
We dont expect in the before block, we should be expecting in an `it` block.

2022-07-13 09:32 UTC, moizmb commented on spec/frederick_api/v2/helpers/paginator_spec.rb
> +    it 'fetch the next link' do
```suggestion
    it 'fetches the next link' do
```

2022-07-13 10:29 UTC, merged